# Generated by Django 4.0.5 on 2022-06-10 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0011_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post_date',
            new_name='date_added',
        ),
    ]
